print("Welcome to the Band Name Generator")
print("What's the name of your city you grew up in?")
city_name = input()
print("What's your pet's name?")
pet_name = input()
print(f"Your Band name could be {city_name} {pet_name}")